//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PensumTree.EntityFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class pensumEntities : DbContext
    {
        public pensumEntities()
            : base("name=pensumEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<carrera> carreras { get; set; }
        public virtual DbSet<escuela> escuelas { get; set; }
        public virtual DbSet<facultad> facultads { get; set; }
        public virtual DbSet<materia> materias { get; set; }
        public virtual DbSet<pensum> pensums { get; set; }
        public virtual DbSet<plan> plans { get; set; }
        public virtual DbSet<tipo_carrera> tipo_carrera { get; set; }
    }
}
