//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PensumTree.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class pensum
    {
        public long id { get; set; }
        public long idPlan { get; set; }
        public long idMateria { get; set; }
        public long corr { get; set; }
        public long ciclo { get; set; }
        public bool estado { get; set; }
    
        public virtual materia materia { get; set; }
        public virtual plan plan { get; set; }
    }
}
